name: Build

on: [push]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - name: Obtain latest version of the repository
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.6'
    - name: Install requirements with PIP
      run: pip install requirements.txt
    - name: Build Open Shop Channel Downloader
      run: pyinstaller.exe --onefile --icon=oscicon.ico osc-dl.py
    - name: Publish Build Artifacts
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.os }}
        path: dist
