name: Check

on: [push]

jobs:
  Check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - name: Obtain latest version of the repository
      uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8.2'
    - name: Install requirements with PIP
      run: pip install -r requirements.txt
    - name: Install pyinstaller
      run: pip install pyinstaller
    - name: Build Open Shop Channel Downloader
      run: pyinstaller --onefile --icon=oscicon.ico osc-dl.py
    - name: Perform Download Test
      run: python ./tests/downloadtest.py
